# Tổng quan về bộ dữ liệu
- Nguồn dữ liệu được thu thập từ API danh mục chuột máy tính của Phong Vũ: https://discovery.tekoapis.com/api/v2/search-skus-v2
- Kích thước: 500 điểm dữ liệu (sản phẩm) với 8 trường thông tin
- Các thuộc tính của bộ dữ liệu:
   + ProductId: Mã định danh trên hệ thống API
   + sku: Mã định danh sản phẩm trong kho hàng
   + Name: Tên sản phẩm
   + Brand: Thương hiệu
   + Retail_price: Giá niêm yết (VND)
   + Latest_price: Giá bán thực tế sau giảm giá (VND)
   + Discount_Percent: Phần trăm giảm giá
   + Discount_Amount: Số tiền giảm giá (VND)

In [20]:
import pandas as pd

df = pd.read_csv('Chuot_PhongVu.csv')
print(f"Tổng điểm dữ liệu: {len(df)}")
display(df.head())

Tổng điểm dữ liệu: 500

,ProductId,sku,Name,Brand,Retail_Price,Latest_Price,Discount_Percent,Discount_Amount
0,899085,260903354,Chuột Gaming không dây Logitech G304 X Lightsp...,Logitech,1250000,1250000,0,0
1,899085,260903355,Chuột Gaming không dây Logitech G304 X Lightsp...,Logitech,1250000,1250000,0,0
2,883304,260902608,Chuột không dây ASUS Marshmallow MD100 Lite Si...,Asus,659000,390000,41,269000
3,862671,260902454,Chuột Gaming không dây ATK Blazing Sky X1 V2 U...,ATK,2490000,1349000,46,1141000
4,897972,260902437,Chuột không dây AULA AM212 (Hồng),Aula,169000,109000,36,60000

In [14]:
print("--- THÔNG TIN CÁC CỘT DỮ LIỆU ---")
df.info()

print("\n--- KIỂM TRA GIÁ TRỊ NULL ---")
print(df.isnull().sum())

print("\n--- KIỂM TRA TRÙNG LẶP ---")
print(f"Số dòng bị trùng lặp: {df.duplicated().sum()}")

--- THÔNG TIN CÁC CỘT DỮ LIỆU ---
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ProductId         500 non-null    int64
 1   sku               500 non-null    int64
 2   Name              500 non-null    str
 3   Brand             500 non-null    str
 4   Retail_Price      500 non-null    int64
 5   Latest_Price      500 non-null    int64
 6   Discount_Percent  500 non-null    int64
 7   Discount_Amount   500 non-null    int64
dtypes: int64(6), str(2)
memory usage: 31.4 KB

--- KIỂM TRA GIÁ TRỊ NULL ---
ProductId           0
sku                 0
Name                0
Brand               0
Retail_Price        0
Latest_Price        0
Discount_Percent    0
Discount_Amount     0
dtype: int64

--- KIỂM TRA TRÙNG LẶP ---
Số dòng bị trùng lặp: 0

In [18]:
cols = ['Retail_Price', 'Latest_Price', 'Discount_Percent', 'Discount_Amount']

print("--- THỐNG KÊ MÔ TẢ ---")
display(df[cols].describe().T[['mean', '50%', 'min', 'max', 'std']].rename(columns={'50%': 'median'}))

--- THỐNG KÊ MÔ TẢ ---

                       mean    median      min        max        std
Retail_Price     1480494.00 868500.00 72000.00 8990000.00 1494875.82
Latest_Price     1063282.00 599000.00 69000.00 8990000.00 1103942.65
Discount_Percent      26.32     26.00     0.00      57.00      14.09
Discount_Amount   417212.00 202500.00     0.00 3040000.00  505066.01

In [19]:
print("--- TOP 10 THƯƠNG HIỆU PHỔ BIẾN NHẤT ---")
brand_summary = df['Brand'].value_counts().reset_index()
brand_summary.columns = ['Thương hiệu', 'Số lượng sản phẩm']
brand_summary['Tỷ lệ (%)'] = (brand_summary['Số lượng sản phẩm'] / len(df) * 100).round(2)

display(brand_summary.head(10))

--- TOP 10 THƯƠNG HIỆU PHỔ BIẾN NHẤT ---

  Thương hiệu  Số lượng sản phẩm  Tỷ lệ (%)
0    Logitech                 81      16.20
1         ATK                 80      16.00
2      Inphic                 58      11.60
3       Dareu                 36       7.20
4       Razer                 29       5.80
5      Mchose                 19       3.80
6       Mofii                 18       3.60
7        Aula                 17       3.40
8      Fuhlen                 17       3.40
9          HP                 17       3.40